<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>1,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>2,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>3,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>1,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>2,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>3,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>1,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>2,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>3,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>1,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>2,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>5,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>1,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>2,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>5,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>1,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>2,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        DB::table('transactions')->insert([
            'user_id'=>1,
            'crowdfunding_id'=>3,
            'fund'=>123123123,
            'image'=>'/storage/images/testmbanking.jpg',
            'status'=>1,
        ]);
        
    }
}
